version: '3.8'

services:
  bilka-monitor:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./test_results:/app/test_results
    environment:
      - DATABASE_URL=sqlite:///data/bilka_prices.db
      - PYTHONPATH=/app
      - USE_MOCK_SCRAPER=true
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bilka-network

  # Optional: PostgreSQL database (uncomment to use instead of SQLite)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: bilka_prices
  #     POSTGRES_USER: bilka_user
  #     POSTGRES_PASSWORD: bilka_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - bilka-network

networks:
  bilka-network:
    driver: bridge

volumes:
  postgres_data: