selectors:
  # Main product container - each product card
  product_container: "a.product-card"
  
  # Product details
  product_name: ".v-card__title"
  product_description: ".description-text"
  
  # Pricing selectors
  price_before: ".before-price"  # Original price (før)
  price_current: ".after-price"  # Current/sale price
  
  # Discount badge
  discount_badge: ".sticker__promotionSaving"  # Contains "Spar X%"
  
  # Images and URLs
  product_image: ".v-image__image"
  product_url: "a.product-card"  # The href attribute
  
  # Availability
  availability: ".text-right"  # Stock status text
  store_stock: ".store-stock"  # Click&Collect availability
  
  # Brand info
  brand: ".product-brand"  # May not always be present

patterns:
  price_regex: "(\\d+[,.]\\d{2})"
  discount_regex: "(-?\\d+)%"
  currency: "kr\\.|DKK"

categories:
  electronics:
    url_pattern: "/elektronik"
    subcategories:
      - "mobiltelefoner"
      - "computere"
      - "tv-og-lyd"
  home:
    url_pattern: "/hjem-og-interior"
    subcategories:
      - "køkken"
      - "bad"
      - "møbler"
  fashion:
    url_pattern: "/mode"
    subcategories:
      - "dame"
      - "herre"
      - "børn"
  sports:
    url_pattern: "/sport-og-fritid"
    subcategories:
      - "fitness"
      - "outdoor"
      - "cykler"

validation:
  max_price: 100000  # Maximum expected price in DKK
  min_price: 0.01    # Minimum expected price in DKK
  max_discount: 95   # Maximum expected discount percentage